version: "3"

services:
  app:
    image: nginx:stable
    ports:
      - "${PROXY_PORT}:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:cached
      - ../data/sites:/etc/nginx/sites:cached
    networks:
      proxy-network: {}

networks:
  proxy-network:
    external: true