version: "3"

services:
  proxy:
    image: nginx:stable
    container_name: proxy
    ports:
      - "${PROXY_PORT}:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ../data/sites:/etc/nginx/sites
    networks:
      proxy-network: {}

networks:
  proxy-network:
    external: true